project:
  type: website

website:
  title: "Ecoeficiencia combinado con LCA y DEA"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

